CREATE TABLE "candidate_profile" (
	"user_id" text PRIMARY KEY NOT NULL,
	"domain" text NOT NULL,
	"primary_role" text NOT NULL,
	"highest_education" text NOT NULL,
	"current_status" text NOT NULL,
	"years_of_experience_min" integer NOT NULL,
	"years_of_experience_max" integer,
	"professional_bio" text NOT NULL,
	"country" text NOT NULL,
	"portfolio_url" text,
	"github_url" text,
	"linkedin_url" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "candidate_profile" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "candidate_profile_tag" (
	"candidate_user_id" text NOT NULL,
	"tag_id" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "candidate_profile_tag_candidate_user_id_tag_id_pk" PRIMARY KEY("candidate_user_id","tag_id")
);
--> statement-breakpoint
ALTER TABLE "candidate_profile_tag" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "recruiter_profile" (
	"user_id" text PRIMARY KEY NOT NULL,
	"organization_name" text NOT NULL,
	"organization_size" text NOT NULL,
	"industry" text NOT NULL,
	"country" text NOT NULL,
	"company_website" text,
	"llm_provider" text NOT NULL,
	"llm_api_key" text NOT NULL,
	"default_model" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "recruiter_profile" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "recruiter_profile_tag" (
	"recruiter_user_id" text NOT NULL,
	"tag_id" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "recruiter_profile_tag_recruiter_user_id_tag_id_pk" PRIMARY KEY("recruiter_user_id","tag_id")
);
--> statement-breakpoint
ALTER TABLE "recruiter_profile_tag" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "tag" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tag_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"type" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "tag_name_unique" UNIQUE("name")
);
--> statement-breakpoint
ALTER TABLE "candidate_profile" ADD CONSTRAINT "candidate_profile_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "candidate_profile_tag" ADD CONSTRAINT "candidate_profile_tag_candidate_user_id_candidate_profile_user_id_fk" FOREIGN KEY ("candidate_user_id") REFERENCES "public"."candidate_profile"("user_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "candidate_profile_tag" ADD CONSTRAINT "candidate_profile_tag_tag_id_tag_id_fk" FOREIGN KEY ("tag_id") REFERENCES "public"."tag"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "recruiter_profile" ADD CONSTRAINT "recruiter_profile_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "recruiter_profile_tag" ADD CONSTRAINT "recruiter_profile_tag_recruiter_user_id_recruiter_profile_user_id_fk" FOREIGN KEY ("recruiter_user_id") REFERENCES "public"."recruiter_profile"("user_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "recruiter_profile_tag" ADD CONSTRAINT "recruiter_profile_tag_tag_id_tag_id_fk" FOREIGN KEY ("tag_id") REFERENCES "public"."tag"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "candidate_profile_tag_tagId_idx" ON "candidate_profile_tag" USING btree ("tag_id");--> statement-breakpoint
CREATE INDEX "recruiter_profile_tag_tagId_idx" ON "recruiter_profile_tag" USING btree ("tag_id");--> statement-breakpoint
CREATE INDEX "tag_name_idx" ON "tag" USING btree ("name");--> statement-breakpoint
CREATE INDEX "tag_type_idx" ON "tag" USING btree ("type");--> statement-breakpoint
CREATE POLICY "Users can manage their candidate profile" ON "candidate_profile" AS PERMISSIVE FOR ALL TO "app_user" USING ((user_id = current_setting('app.current_user_id', true))) WITH CHECK ((user_id = current_setting('app.current_user_id', true)));--> statement-breakpoint
CREATE POLICY "Users can manage their profile tags" ON "candidate_profile_tag" AS PERMISSIVE FOR ALL TO "app_user" USING ((candidate_user_id = current_setting('app.current_user_id', true))) WITH CHECK ((candidate_user_id = current_setting('app.current_user_id', true)));--> statement-breakpoint
CREATE POLICY "Users can manage their recruiter profile" ON "recruiter_profile" AS PERMISSIVE FOR ALL TO "app_user" USING ((user_id = current_setting('app.current_user_id', true))) WITH CHECK ((user_id = current_setting('app.current_user_id', true)));--> statement-breakpoint
CREATE POLICY "Users can manage their recruiter tags" ON "recruiter_profile_tag" AS PERMISSIVE FOR ALL TO "app_user" USING ((recruiter_user_id = current_setting('app.current_user_id', true))) WITH CHECK ((recruiter_user_id = current_setting('app.current_user_id', true)));